// Generated by https://quicktype.io
import 'package:json_annotation/json_annotation.dart';

part 'get_posts_request_model.g.dart';

@JsonSerializable()

class GetPostsRequestModel {
  String? userId;
  String? lastPostDate;
  final int postsAmount;

  GetPostsRequestModel({
    this.userId,
    this.lastPostDate,
    required this.postsAmount,
  });

      factory GetPostsRequestModel.fromJson(Map<String, dynamic> json) =>
      _$GetPostsRequestModelFromJson(json);

  Map<String, dynamic> toJson() => _$GetPostsRequestModelToJson(this);
}
